name: "Combine PRs"

on:
  schedule:
    - cron: "0 0 * * *" # Runs every midnight
  workflow_dispatch:
    inputs:
      branchPrefix:
        description: "Branch prefix to find combinable PRs based on"
        required: true
        default: "dependabot"
      mustBeMergeable:
        description: "Only combine PRs that are green (pass checks) and with state clean"
        required: true
        type: boolean
        default: true
      combineBranchName:
        description: "Name of the branch to combine PRs into"
        required: true
        default: "combine-prs-branch"
      ignoreLabel:
        description: "Exclude PRs with this label"
        required: true
        default: "nocombine"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "combine-prs"
  combine-prs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: |
          USER_INPUT_BRANCH_PREFIX='${{ github.event.inputs.branchPrefix }}'
          # Use user input or fall back to "dependabot"
          echo "BRANCH_PREFIX=${USER_INPUT_BRANCH_PREFIX:-'dependabot'}" >> $GITHUB_ENV
          # use ${{ env.BRANCH_PREFIX }} in your action, value will be always provided
          USER_INPUT_MUST_BE_MERGEABLE=${{ github.event.inputs.mustBeMergeable }}
          echo "MUST_BE_MERGEABLE=${USER_INPUT_MUST_BE_MERGEABLE:-true}" >> $GITHUB_ENV
          USER_INPUT_COMBINE_BRANCH_NAME='${{ github.event.inputs.combineBranchName }}'
          echo "COMBINE_BRANCH=${USER_INPUT_COMBINE_BRANCH_NAME:-'combine-prs-branch'}" >> $GITHUB_ENV
          USER_INPUT_IGNORE_LABEL='${{ github.event.inputs.ignoreLabel }}'

          echo "IGNORE_LABEL=${USER_INPUT_IGNORE_LABEL:-'nocombine'}" >> $GITHUB_ENV
      - uses: actions/github-script@v3
        id: fetch-branch-names
        name: Fetch branch names
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pulls = await github.paginate('GET /repos/:owner/:repo/pulls', {
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            branches = [];
            prs = [];
            base_branch = null;
            for (const pull of pulls) {
              const branch = pull['head']['ref'];
              console.log('Pull for branch: ' + branch);
              if (branch.startsWith('${{ env.BRANCH_PREFIX }}')) {
                console.log('Branch matched: ' + branch);
                statusOK = true;
                if(${{ env.MUST_BE_MERGEABLE }}) {
                  const pullNumber = pull['number'];
                  const branchPullRequest = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pullNumber
                  });
                  console.log('Checking mergeability: ' + branchPullRequest['html_url']);
                  console.log('Mergeability API Link: ' + branchPullRequest['url']);
                  const isMergeable = branchPullRequest['data']['mergeable']
                  const mergeableState = branchPullRequest['data']['mergeable_state']
                  if (!(isMergeable && mergeableState === 'clean')) {
                    statusOK = false;
                  }
                  console.log('Mergeable is ' + isMergeable + ' with mergeable state ' + mergeableState);
                }
                console.log('Checking labels: ' + branch);
                const labels = pull['labels'];
                for(const label of labels) {
                  const labelName = label['name'];
                  console.log('Checking label: ' + labelName);
                  if(labelName == '${{ env.IGNORE_LABEL }}') {
                    console.log('Discarding ' + branch + ' with label ' + labelName);
                    statusOK = false;
                  }
                }
                if (statusOK) {
                  console.log('Adding branch to array: ' + branch);
                  branches.push(branch);
                  prs.push('#' + pull['number'] + ' ' + pull['title']);
                  base_branch = pull['base']['ref'];
                }
              }
            }

            if (branches.length == 0) {
              core.setFailed('No PRs/branches matched criteria');
              return;
            }

            core.setOutput('base-branch', base_branch);
            core.setOutput('prs-string', prs.join('\n'));

            combined = branches.join(' ')
            console.log('Combined: ' + combined);
            return combined
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0
      # Creates a branch with other PR branches merged together
      - name: Created combined branch
        env:
          BASE_BRANCH: ${{ steps.fetch-branch-names.outputs.base-branch }}
          BRANCHES_TO_COMBINE: ${{ steps.fetch-branch-names.outputs.result }}
          COMBINE_BRANCH_NAME: ${{ env.COMBINE_BRANCH }}
        run: |
          echo "$BRANCHES_TO_COMBINE"
          sourcebranches="${BRANCHES_TO_COMBINE%\"}"
          sourcebranches="${sourcebranches#\"}"

          basebranch="${BASE_BRANCH%\"}"
          basebranch="${basebranch#\"}"

          git config pull.rebase false
          git config user.name github-actions
          git config user.email github-actions@github.com

          git branch $COMBINE_BRANCH_NAME $basebranch
          git checkout $COMBINE_BRANCH_NAME
          git pull origin $sourcebranches --no-edit
          git push origin $COMBINE_BRANCH_NAME
      # Creates a PR with the new combined branch
      - uses: actions/github-script@v3
        name: Create Combined Pull Request
        env:
          PRS_STRING: ${{ steps.fetch-branch-names.outputs.prs-string }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prString = process.env.PRS_STRING;
            const body = 'This PR was created by the Combine PRs action by combining the following PRs:\n' + prString;
            await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Combined PR',
              head: '${{ github.event.inputs.combineBranchName }}',
              base: '${{ steps.fetch-branch-names.outputs.base-branch }}',
              body: body
            });
